name: Build Docs Test
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'src/**/lv*.h'
      - 'examples/**'
      - 'demos/**'
      - 'scripts/build_html_examples.sh'
      - 'scripts/find_version.sh'
  push:
    branches:
      - master
      - 'release/*'
      - 'docs/*'
    paths:
      - 'docs/**'
      - 'src/**/lv*.h'
      - 'examples/**'
      - 'demos/**'
      - 'scripts/build_html_examples.sh'
      - 'scripts/find_version.sh'

# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
# Ensure that only one commit will be running tests at a time on each PR
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  EM_VERSION: 2.0.4
  EM_CACHE_FOLDER: 'emsdk-cache'
jobs:
  build-only:
    if: github.repository == 'vwheeler63/lvgl'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Cache Python packages
        uses: actions/cache@v5
        with:
          # Cache the Python package environment, excluding pip and setuptools installed by setup-python
          path: |
            ~/.cache/pip
            ${{ env.pythonLocation }}/bin/*
            ${{ env.pythonLocation }}/include
            ${{ env.pythonLocation }}/lib/python*/site-packages/*
            !${{ env.pythonLocation }}/bin/pip*
            !${{ env.pythonLocation }}/lib/python*/site-packages/pip*
            !${{ env.pythonLocation }}/lib/python*/site-packages/setuptools*
          key: ${{ env.pythonLocation }}-${{ hashFiles('docs/requirements.txt') }}
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          # Remember these for possible future use.
          # texlive-xetex texlive-binaries texlive-lang-english latexmk fonts-freefont-otf
      - name: Install Requirements
        run: |
          pip install -r docs/requirements.txt
      - name: Build Docs
        run: docs/build.py html
      - name: Retrieve Version
        run: |
          echo "VERSION_NAME=$(scripts/find_version.sh)" >> "$GITHUB_OUTPUT"
        id: version
        # Result:  version from `lv_version.h` is now available as
        # ${{ steps.version.outputs.VERSION_NAME }}, used in `Deploy to subfolder` step below.
      - name: Validate Version
        run: |
          echo Version: ${{ steps.version.outputs.VERSION_NAME }}

